package com.gotocompany.dagger.core.source.config;

import com.google.gson.annotations.JsonAdapter;
import com.gotocompany.dagger.core.enumeration.KafkaConnectorTypesMetadata;
import com.gotocompany.dagger.core.source.config.adapter.DaggerKafkaConsumerAdditionalConfigurationsAdaptor;
import com.gotocompany.dagger.core.source.config.adapter.DaggerSASLMechanismAdaptor;
import com.gotocompany.dagger.core.source.config.adapter.DaggerSSLKeyStoreFileTypeAdaptor;
import com.gotocompany.dagger.core.source.config.adapter.DaggerSSLProtocolAdaptor;
import com.gotocompany.dagger.core.source.config.adapter.DaggerSSLTrustStoreFileTypeAdaptor;
import com.gotocompany.dagger.core.source.config.adapter.DaggerSecurityProtocolAdaptor;
import com.gotocompany.dagger.core.source.config.adapter.FileDateRangeAdaptor;
import com.gotocompany.dagger.core.source.config.adapter.SourceParquetFilePathsAdapter;
import com.gotocompany.dagger.core.source.config.models.SourceType;
import com.gotocompany.dagger.core.source.parquet.SourceParquetReadOrderStrategy;
import com.gotocompany.dagger.core.source.parquet.SourceParquetSchemaMatchStrategy;
import com.gotocompany.dagger.core.source.config.models.SourceDetails;
import com.gotocompany.dagger.core.source.config.models.SourceName;
import com.gotocompany.dagger.core.source.config.models.TimeRangePool;
import com.gotocompany.dagger.core.utils.KafkaConfigUtil;
import org.apache.flink.connector.kafka.source.enumerator.initializer.OffsetsInitializer;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.gotocompany.dagger.common.configuration.Configuration;
import lombok.Getter;
import org.apache.kafka.clients.consumer.OffsetResetStrategy;

import java.io.StringReader;
import java.util.Map;
import java.util.Objects;
import java.util.Properties;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static com.gotocompany.dagger.common.core.Constants.INPUT_STREAMS;
import static com.gotocompany.dagger.common.core.Constants.STREAM_INPUT_SCHEMA_PROTO_CLASS;
import static com.gotocompany.dagger.common.core.Constants.STREAM_INPUT_SCHEMA_TABLE;
import static com.gotocompany.dagger.core.utils.Constants.*;

/**
 * Configuration model describing a single input stream consumed by a Dagger job.
 *
 * <p>Dagger reads its input definitions from the {@code INPUT_STREAMS} configuration, whose value is
 * a JSON array of stream objects. Each element is deserialized by Gson into a {@code StreamConfig}
 * via {@link #parse(Configuration)}, which additionally runs the {@link StreamConfigValidator}
 * checks. A single instance captures everything needed to wire up one source: Kafka connection and
 * security settings (bootstrap servers, consumer group, SSL/SASL), the input schema (Protobuf class
 * or JSON schema and the event-timestamp field), the data type ({@code PROTO} or {@code JSON}), the
 * ordered list of backing {@link SourceDetails sources}, and Parquet-specific options (file paths,
 * read order, schema-match strategy, and date-range filter).
 *
 * <p>Several string fields are validated and normalized during deserialization through Gson
 * {@code @JsonAdapter} type adapters in the {@code adapter} package (for example SSL protocol,
 * keystore/truststore type, security protocol, and SASL mechanism), so invalid values fail fast at
 * job startup. Most getters are generated by Lombok; a handful are hand-written to supply defaults.
 */
public class StreamConfig {
    /** Shared, pretty-printing Gson instance used to (de)serialize stream configs and Kafka props. */
    private static final Gson GSON = new GsonBuilder()
            .enableComplexMapKeySerialization()
            .setPrettyPrinting()
            .create();

    /** Lower-cased key prefix identifying serialized Kafka consumer settings to expose as client props. */
    private static final String KAFKA_PREFIX = "source_kafka_consumer_config_";

    /** Password of the private key stored in the Kafka consumer keystore ({@code ssl.key.password}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_KEY_PASSWORD_KEY)
    @Getter
    private String sslKeyPassword;

    /** Filesystem path to the SSL keystore presented by the Kafka consumer ({@code ssl.keystore.location}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_KEYSTORE_LOCATION_KEY)
    @Getter
    private String sslKeystoreLocation;

    /** Password protecting the Kafka consumer SSL keystore ({@code ssl.keystore.password}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_KEYSTORE_PASSWORD_KEY)
    @Getter
    private String sslKeystorePassword;

    /**
     * File format of the Kafka consumer SSL keystore ({@code ssl.keystore.type}).
     *
     * <p>Validated during deserialization by {@link DaggerSSLKeyStoreFileTypeAdaptor} against the
     * supported store types ({@code JKS}, {@code PKCS12}, {@code PEM}).
     */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_KEYSTORE_TYPE_KEY)
    @Getter
    @JsonAdapter(value = DaggerSSLKeyStoreFileTypeAdaptor.class)
    private String sslKeystoreType;

    /**
     * SSL/TLS protocol version negotiated by the Kafka consumer ({@code ssl.protocol}).
     *
     * <p>Validated during deserialization by {@link DaggerSSLProtocolAdaptor} against the supported
     * protocol versions.
     */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_PROTOCOL_KEY)
    @Getter
    @JsonAdapter(value = DaggerSSLProtocolAdaptor.class)
    private String sslProtocol;

    /** Filesystem path to the SSL truststore used by the Kafka consumer ({@code ssl.truststore.location}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_TRUSTSTORE_LOCATION_KEY)
    @Getter
    private String sslTruststoreLocation;

    /** Password protecting the Kafka consumer SSL truststore ({@code ssl.truststore.password}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_TRUSTSTORE_PASSWORD_KEY)
    @Getter
    private String sslTruststorePassword;

    /**
     * File format of the Kafka consumer SSL truststore ({@code ssl.truststore.type}).
     *
     * <p>Validated during deserialization by {@link DaggerSSLTrustStoreFileTypeAdaptor} against the
     * supported store types ({@code JKS}, {@code PKCS12}, {@code PEM}).
     */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SSL_TRUSTSTORE_TYPE_KEY)
    @Getter
    @JsonAdapter(value = DaggerSSLTrustStoreFileTypeAdaptor.class)
    private String sslTruststoreType;

    /** Kafka topic selector for this stream, interpreted as a Java regular expression; see {@link #getTopicPattern()}. */
    @SerializedName(STREAM_SOURCE_KAFKA_TOPIC_NAMES_KEY)
    @Getter
    private String kafkaTopicNames;

    /** Fully-qualified name of the Protobuf message class describing the input schema (used for {@code PROTO} streams). */
    @SerializedName(STREAM_INPUT_SCHEMA_PROTO_CLASS)
    @Getter
    private String protoClass;

    /** Name of the Flink SQL table under which this stream is registered for querying. */
    @SerializedName(STREAM_INPUT_SCHEMA_TABLE)
    @Getter
    private String schemaTable;

    /** Whether the Kafka consumer commits offsets automatically ({@code enable.auto.commit}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_COMMIT_ENABLE_KEY)
    @Getter
    private String autoCommitEnable;

    /**
     * Kafka offset-reset policy applied when no committed offset exists for the consumer group
     * ({@code auto.offset.reset}), for example {@code latest} or {@code earliest}.
     *
     * <p>Defaults to {@code latest} when unset via {@link #getAutoOffsetReset()}.
     */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET_KEY)
    private String autoOffsetReset;

    /** Kafka consumer group id used when subscribing to the configured topics ({@code group.id}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_GROUP_ID_KEY)
    @Getter
    private String consumerGroupId;

    /** Comma-separated list of Kafka broker {@code host:port} pairs ({@code bootstrap.servers}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_BOOTSTRAP_SERVERS_KEY)
    @Getter
    private String bootstrapServers;

    /**
     * Security protocol used to connect to Kafka ({@code security.protocol}).
     *
     * <p>Validated during deserialization by {@link DaggerSecurityProtocolAdaptor} against the
     * supported protocols ({@code SASL_PLAINTEXT}, {@code SASL_SSL}, {@code SSL}).
     */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SECURITY_PROTOCOL_KEY)
    @Getter
    @JsonAdapter(value = DaggerSecurityProtocolAdaptor.class)
    private String securityProtocol;

    /**
     * SASL mechanism used to authenticate the Kafka consumer ({@code sasl.mechanism}).
     *
     * <p>Validated during deserialization by {@link DaggerSASLMechanismAdaptor} against the supported
     * mechanisms ({@code PLAIN}, {@code SCRAM-SHA-256}, {@code SCRAM-SHA-512}).
     */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SASL_MECHANISM_KEY)
    @JsonAdapter(value = DaggerSASLMechanismAdaptor.class)
    @Getter
    private String saslMechanism;

    /** JAAS login configuration string supplying SASL credentials ({@code sasl.jaas.config}). */
    @SerializedName(SOURCE_KAFKA_CONSUMER_CONFIG_SASL_JAAS_CONFIG_KEY)
    @Getter
    private String saslJaasConfig;

    /** Logical name of this input stream as referenced elsewhere in the Dagger job configuration. */
    @SerializedName(STREAM_INPUT_STREAM_NAME_KEY)
    @Getter
    private String kafkaName;

    /** JSON schema describing the input records when the stream's data type is {@code JSON}. */
    @SerializedName(STREAM_INPUT_SCHEMA_JSON_SCHEMA_KEY)
    @Getter
    private String jsonSchema;

    /** Name of the JSON field carrying the event timestamp used for watermarking {@code JSON} streams. */
    @SerializedName(STREAM_INPUT_SCHEMA_JSON_EVENT_TIMESTAMP_FIELD_NAME_KEY)
    @Getter
    private String jsonEventTimestampFieldName;

    /** Index (within the configured schema) of the field carrying the event timestamp. */
    @SerializedName(STREAM_INPUT_SCHEMA_EVENT_TIMESTAMP_FIELD_INDEX_KEY)
    @Getter
    private String eventTimestampFieldIndex;

    /** Input record encoding for this stream, either {@code PROTO} or {@code JSON}; defaults to {@code PROTO} via {@link #getDataType()}. */
    @SerializedName(STREAM_INPUT_DATATYPE)
    private String dataType;

    /**
     * Ordered list of backing sources for this stream, each pairing a {@link SourceName} with a
     * {@link SourceType} (for example a bounded Parquet backfill followed by an unbounded Kafka feed).
     *
     * <p>Defaults to a single unbounded Kafka consumer source when unset via {@link #getSourceDetails()}.
     */
    @SerializedName(STREAM_SOURCE_DETAILS_KEY)
    private SourceDetails[] sourceDetails;

    /**
     * Parquet file or directory paths to read when a Parquet source is configured.
     *
     * <p>Each entry is trimmed of surrounding whitespace during deserialization by
     * {@link SourceParquetFilePathsAdapter}.
     */
    @SerializedName(STREAM_SOURCE_PARQUET_FILE_PATHS_KEY)
    @Getter
    @JsonAdapter(value = SourceParquetFilePathsAdapter.class)
    private String[] parquetFilePaths;

    /** Order in which Parquet files are read; defaults to {@code EARLIEST_TIME_URL_FIRST} via {@link #getParquetFilesReadOrderStrategy()}. */
    @SerializedName(STREAM_SOURCE_PARQUET_READ_ORDER_STRATEGY_KEY)
    private SourceParquetReadOrderStrategy parquetFilesReadOrderStrategy;

    /** Strategy used to reconcile each Parquet file's schema with the configured schema while reading. */
    @SerializedName(STREAM_SOURCE_PARQUET_SCHEMA_MATCH_STRATEGY_KEY)
    @Getter
    private SourceParquetSchemaMatchStrategy parquetSchemaMatchStrategy;

    /**
     * Additional Kafka consumer properties merged into the generated client configuration.
     *
     * <p>During deserialization {@link DaggerKafkaConsumerAdditionalConfigurationsAdaptor} validates
     * that every key matches the consumer prefix and drops entries with {@code null} values.
     */
    @SerializedName(SOURCE_KAFKA_CONSUMER_ADDITIONAL_CONFIGURATIONS)
    @JsonAdapter(value = DaggerKafkaConsumerAdditionalConfigurationsAdaptor.class)
    @Getter
    private Map<String, String> additionalConsumerConfigurations;

    /**
     * Time window(s) used to restrict which Parquet files are read, based on the timestamps in their
     * paths.
     *
     * <p>Parsed from a semicolon-separated list of ISO-8601 timestamp pairs by
     * {@link FileDateRangeAdaptor} into a {@link TimeRangePool}.
     */
    @SerializedName(STREAM_SOURCE_PARQUET_FILE_DATE_RANGE_KEY)
    @JsonAdapter(FileDateRangeAdaptor.class)
    @Getter
    private TimeRangePool parquetFileDateRange;

    /**
     * Returns the input record encoding for this stream, defaulting to {@code PROTO} when unspecified.
     *
     * <p>The first call lazily caches the {@code PROTO} default back onto the field so subsequent
     * serialization reflects the resolved value.
     *
     * @return the configured data type, or {@code "PROTO"} when none was provided
     */
    public String getDataType() {
        if (dataType == null) {
            dataType = "PROTO";
        }
        return dataType;
    }

    /**
     * Returns the backing sources for this stream, defaulting to a single unbounded Kafka consumer.
     *
     * <p>When no {@code sourceDetails} were configured, a one-element array consisting of a
     * {@link SourceName#KAFKA_CONSUMER} source with {@link SourceType#UNBOUNDED} is returned so legacy
     * Kafka-only streams keep working without explicit source declarations.
     *
     * @return the configured source details, or the default Kafka-consumer source when none were set
     */
    public SourceDetails[] getSourceDetails() {
        if (sourceDetails == null) {
            return new SourceDetails[]{new SourceDetails(SourceName.KAFKA_CONSUMER, SourceType.UNBOUNDED)};
        } else {
            return sourceDetails;
        }
    }

    /**
     * Returns the Parquet read-order strategy, defaulting to earliest-timestamp-first when unset.
     *
     * @return the configured {@link SourceParquetReadOrderStrategy}, or
     *         {@link SourceParquetReadOrderStrategy#EARLIEST_TIME_URL_FIRST} when none was provided
     */
    public SourceParquetReadOrderStrategy getParquetFilesReadOrderStrategy() {
        if (parquetFilesReadOrderStrategy == null) {
            return SourceParquetReadOrderStrategy.EARLIEST_TIME_URL_FIRST;
        } else {
            return parquetFilesReadOrderStrategy;
        }
    }

    /**
     * Returns the Kafka {@code auto.offset.reset} policy, defaulting to {@code latest} when unspecified.
     *
     * <p>The first call lazily caches the {@code latest} default back onto the field.
     *
     * @return the configured offset-reset policy, or {@code "latest"} when none was provided
     */
    public String getAutoOffsetReset() {
        if (autoOffsetReset == null) {
            autoOffsetReset = "latest";
        }
        return autoOffsetReset;
    }

    /**
     * Parses the {@code INPUT_STREAMS} configuration value into an array of validated stream configs.
     *
     * <p>The configuration holds a JSON array of stream objects (empty string when absent). Each
     * element is deserialized with Gson and then passed through
     * {@link StreamConfigValidator#validateSourceDetails(StreamConfig)} and
     * {@link StreamConfigValidator#validateParquetDataSourceStreamConfigs(StreamConfig)}, so malformed
     * source declarations cause the job to fail fast during startup.
     *
     * @param configuration the Dagger job configuration to read the {@code INPUT_STREAMS} value from
     * @return one validated {@code StreamConfig} per element of the configured JSON array
     */
    public static StreamConfig[] parse(Configuration configuration) {
        String jsonArrayString = configuration.getString(INPUT_STREAMS, "");
        JsonReader reader = new JsonReader(new StringReader(jsonArrayString));
        reader.setLenient(true);

        return Stream.of(GSON.fromJson(jsonArrayString, StreamConfig[].class))
                .map(StreamConfigValidator::validateSourceDetails)
                .map(StreamConfigValidator::validateParquetDataSourceStreamConfigs)
                .toArray(StreamConfig[]::new);
    }

    /**
     * Builds the Kafka client {@link Properties} for this stream's consumer.
     *
     * <p>This config is round-tripped through JSON to a flat map; entries whose key (lower-cased)
     * starts with the {@code source_kafka_consumer_config_} prefix are converted into dotted Kafka
     * property names (see {@link #parseVarName(String, String)}) and copied into the result. Finally
     * {@link #setAdditionalKafkaConsumerConfigs(Properties, Configuration)} applies large-message
     * tuning and any user-supplied extra consumer properties.
     *
     * @param configuration the Dagger job configuration, consulted for large-message handling
     * @return the assembled Kafka consumer properties for this stream
     */
    public Properties getKafkaProps(Configuration configuration) {
        String jsonString = GSON.toJson(this);
        Map<String, String> streamConfigMap = GSON.fromJson(jsonString, Map.class);
        Properties kafkaProps = new Properties();
        streamConfigMap.entrySet()
                .stream()
                .filter(e -> e.getKey().toLowerCase().startsWith(KAFKA_PREFIX))
                .forEach(e -> kafkaProps.setProperty(parseVarName(e.getKey(), KAFKA_PREFIX), e.getValue()));
        setAdditionalKafkaConsumerConfigs(kafkaProps, configuration);
        return kafkaProps;
    }

    /**
     * Converts a serialized consumer-config key into its dotted Kafka property name.
     *
     * <p>The key is lower-cased, the {@code source_kafka_consumer_config_} prefix is stripped, and the
     * remaining underscore-delimited segments are re-joined with dots. For example
     * {@code SOURCE_KAFKA_CONSUMER_CONFIG_BOOTSTRAP_SERVERS} becomes {@code bootstrap.servers}.
     *
     * @param varName     the serialized configuration key to translate
     * @param kafkaPrefix the prefix to remove before splitting (the consumer-config prefix)
     * @return the equivalent dot-separated Kafka client property name
     */
    private String parseVarName(String varName, String kafkaPrefix) {
        String[] names = varName.toLowerCase().replaceAll(kafkaPrefix, "").split("_");
        return String.join(".", names);
    }

    /**
     * Augments the given Kafka properties with large-message tuning and user-supplied extra configs.
     *
     * <p>When large-message consumption is enabled in the job configuration, the consumer's
     * {@code max.partition.fetch.bytes} is raised to the configured default. Any
     * {@link #additionalConsumerConfigurations} present are normalized via
     * {@link KafkaConfigUtil#parseKafkaConfiguration} for the {@link KafkaConnectorTypesMetadata#SOURCE}
     * connector and merged in, overriding earlier values on key collision.
     *
     * @param kafkaProps    the properties to mutate in place with the additional settings
     * @param configuration the Dagger job configuration consulted for large-message handling
     */
    private void setAdditionalKafkaConsumerConfigs(Properties kafkaProps, Configuration configuration) {
        if (configuration.getBoolean(SOURCE_KAFKA_CONSUME_LARGE_MESSAGE_ENABLE_KEY, SOURCE_KAFKA_CONSUME_LARGE_MESSAGE_ENABLE_DEFAULT)) {
            kafkaProps.setProperty(SOURCE_KAFKA_MAX_PARTITION_FETCH_BYTES_KEY, SOURCE_KAFKA_MAX_PARTITION_FETCH_BYTES_DEFAULT);
        }
        if (Objects.nonNull(this.additionalConsumerConfigurations)) {
            Properties additionalKafkaProperties = new Properties();
            additionalKafkaProperties.putAll(this.additionalConsumerConfigurations);
            kafkaProps.putAll(KafkaConfigUtil.parseKafkaConfiguration(KafkaConnectorTypesMetadata.SOURCE, additionalKafkaProperties));
        }
    }

    /**
     * Compiles the configured topic selector into a regular-expression {@link Pattern}.
     *
     * <p>Dagger subscribes to Kafka topics by pattern, so the raw {@code kafkaTopicNames} value is
     * treated as a regex rather than a literal topic list.
     *
     * @return a compiled pattern matching the topics this stream should consume
     */
    public Pattern getTopicPattern() {
        return Pattern.compile(kafkaTopicNames);
    }

    /**
     * Builds the Flink Kafka source starting offset from the committed consumer-group offsets.
     *
     * <p>The returned {@link OffsetsInitializer} resumes from the group's committed offsets and falls
     * back to the configured {@code auto.offset.reset} strategy when no committed offset is available.
     *
     * @return an offsets initializer seeded with committed offsets and the configured reset strategy
     */
    public OffsetsInitializer getStartingOffset() {
        return OffsetsInitializer.committedOffsets(getOffsetResetStrategy());
    }

    /**
     * Maps the configured {@code auto.offset.reset} value onto a Kafka {@link OffsetResetStrategy}.
     *
     * <p>The configured value is upper-cased to match the enum constant names
     * (for example {@code latest} maps to {@link OffsetResetStrategy#LATEST}).
     *
     * @return the offset-reset strategy corresponding to the configured value
     */
    private OffsetResetStrategy getOffsetResetStrategy() {
        return OffsetResetStrategy.valueOf(autoOffsetReset.toUpperCase());
    }
}
